"use strict";
/* =====================================================================
   CodeCraft — music
   ---------------------------------------------------------------------
   Two looping themes, generated by the same Web Audio graph the blips in
   fx.js already use. There is no audio file in this repo and this does not
   add one: a recorded loop is 1-3MB per track, needs a licence you have to
   be able to show a store reviewer, and has to be cached for offline. The
   whole of both themes below is a few hundred bytes of note data.

   It also buys something a recording cannot: the music follows the game.
   Entering a challenge crossfades to a tighter, faster theme in the
   relative minor, and leaving crossfades back.

   Three rules it has to keep:
     1. Never start without a gesture. Browsers suspend AudioContext until
        the user acts, and a game that fights that policy is a game that
        sometimes has no sound at all.
     2. Never drown the blips. sfx() peaks at .08 per note; music sits
        under that and everything routes through one master gain.
     3. Never run when nobody is listening. Hidden tab, muted, or music
        switched off — the scheduler stops, it does not just go quiet.
   ===================================================================== */
(function(){
if(window.__music)return; window.__music=1;

/* ---------------- the two themes ----------------
   MIDI numbers. 60 is middle C. A chord is [root, third, fifth] and the
   arp walks it; `mel` holds one row per bar and eight eighth-note slots
   per row, null for a rest — laid out so a tune can be read down the page
   rather than decoded from step offsets.

   World is C major and Focus is A minor — relative keys, the same seven
   notes, so a crossfade between them can never land on a wrong note. */
const _=null;
const TRACKS={
  /* Chosen from the audition page. The theme before this one ran at 82 BPM
     with ten melody notes across eight bars and no percussion at all, which
     is why it read as slow: not the tempo alone, but a tune that spent half
     its length resting over nothing keeping time. */
  world:{
    bpm:116, bars:8, barsPerChord:1, lead:"triangle", leadGain:.085,
    /* C G Am F | C G F G — one bar each, so the harmony moves at walking
       pace instead of sitting on a chord for two bars at a time. */
    prog:[[48,52,55],[43,47,50],[45,48,52],[41,45,48],
          [48,52,55],[43,47,50],[41,45,48],[43,47,50]],
    bass:{steps:[0,6,8,14],len:.5,gain:.13,wave:"sine"},
    arp:{every:2,pat:[0,2,1,3,2,1,2,0],gain:.04},
    drums:{kick:[0,8],snare:[4,12],hat:[0,2,4,6,8,10,12,14]},
    mel:[[67,69,72,_,74,_,72,_],[71,_,74,_,71,69,67,_],
         [69,72,76,_,74,_,72,_],[72,69,65,_,69,_,_,_],
         [67,69,72,76,79,_,76,_],[74,_,71,_,74,76,74,_],
         [72,69,65,69,72,_,_,_],[67,71,74,_,79,_,_,_]]
  },
  focus:{
    bpm:104, bars:4, barsPerChord:1, lead:"triangle", leadGain:.075,
    /* i - VI - III - VII: the world theme's four chords read from its
       relative minor. Kept as it was — a challenge wants a pulse to work
       against, not a tune to follow. */
    prog:[[45,48,52],[41,45,48],[48,52,55],[43,47,50]],
    bass:{steps:[0,2,4,6,8,10,12,14],len:.42,gain:.12,wave:"sine"},
    arp:{every:1,pat:[0,1,2,1,2,3,2,1,0,1,2,1,2,3,2,1],gain:.045},
    drums:{kick:[],snare:[],hat:[2,6,10,14]},
    mel:[[69,_,_,72,_,_,_,_],[_,_,_,_,_,_,_,_],
         [67,_,_,72,_,_,_,_],[_,_,_,_,_,_,_,_]]
  }
};

const VOL=0.44;                 // master ceiling; sfx peaks at .08 per blip
const LOOKAHEAD=0.30;           // seconds of notes scheduled in advance
const TICK=110;                 // ms between scheduler wake-ups

const midi=n=>440*Math.pow(2,(n-69)/12);

let A=null;                     // the context every node below is built on
let bus=null,mGain=null,echo=null,noise=null;
let timer=null,playing=false,mode="world",track=TRACKS.world;
let step=0,nextT=0,scheduled=0;

/* fx.js owns `actx` and creates it lazily on the first blip. Share it, so
   the game only ever has one AudioContext — Safari caps them and a second
   one is how you get silence on iOS. */
function audio(){
  try{
    if(!actx)actx=new (window.AudioContext||window.webkitAudioContext)();
    A=actx; return actx;
  }catch(_){return null;}
}

function build(a0){
  const a=a0||audio(); if(!a)return false;
  if(!a0&&bus)return true;
  A=a;
  mGain=a.createGain(); mGain.gain.value=0; mGain.connect(a.destination);
  const lp=a.createBiquadFilter();
  lp.type="lowpass"; lp.frequency.value=4200; lp.Q.value=.5;
  lp.connect(mGain);
  bus=a.createGain(); bus.gain.value=1; bus.connect(lp);
  /* One short delay, fed only by the arp. It is the difference between
     "four oscillators" and "a room". */
  const d=a.createDelay(1), fb=a.createGain();
  d.delayTime.value=.26; fb.gain.value=.24;
  d.connect(fb); fb.connect(d); d.connect(bus);
  echo=a.createGain(); echo.gain.value=.5; echo.connect(d);
  // one second of white noise, reused for every hat
  noise=a.createBuffer(1,a.sampleRate,a.sampleRate);
  const ch=noise.getChannelData(0);
  for(let i=0;i<ch.length;i++)ch[i]=Math.random()*2-1;
  return true;
}

function tone(f,t,dur,gain,type,send){
  const a=A;
  const o=a.createOscillator(),g=a.createGain();
  o.type=type; o.frequency.setValueAtTime(f,t);
  g.gain.setValueAtTime(.0001,t);
  g.gain.linearRampToValueAtTime(gain,t+.014);
  g.gain.exponentialRampToValueAtTime(Math.max(gain*.3,.0002),t+dur*.6);
  g.gain.exponentialRampToValueAtTime(.0001,t+dur);
  o.connect(g); g.connect(bus); if(send)g.connect(echo);
  o.start(t); o.stop(t+dur+.06);
  scheduled++;
}
/* Percussion. A pitch sweep is a kick and filtered noise is everything
   else — the whole drum kit is these two functions. */
function kick(t){
  const a=A;
  const o=a.createOscillator(),g=a.createGain();
  o.type="sine";
  o.frequency.setValueAtTime(132,t);
  o.frequency.exponentialRampToValueAtTime(46,t+.11);
  g.gain.setValueAtTime(.24,t);
  g.gain.exponentialRampToValueAtTime(.0001,t+.24);
  o.connect(g); g.connect(bus); o.start(t); o.stop(t+.28);
  scheduled++;
}
function burst(t,dur,type,freq,gain){
  const a=A;
  const s=a.createBufferSource(); s.buffer=noise;
  const f=a.createBiquadFilter(); f.type=type; f.frequency.value=freq;
  const g=a.createGain();
  g.gain.setValueAtTime(gain,t);
  g.gain.exponentialRampToValueAtTime(.0001,t+dur);
  s.connect(f); f.connect(g); g.connect(bus);
  s.start(t); s.stop(t+dur+.02);
  scheduled++;
}
const snare=t=>burst(t,.13,"bandpass",1900,.145);
const hat  =t=>burst(t,.04,"highpass",7600,.045);

/* One 16th note of the loop. Everything is derived from `step`, so the
   loop has no state to drift out of sync. */
function play1(i,t){
  const T=track, bar=Math.floor(i/16), inBar=i%16;
  const ch=T.prog[Math.floor(bar/T.barsPerChord)%T.prog.length];

  if(T.bass.steps.indexOf(inBar)>=0)
    tone(midi(ch[0]-12),t,T.bass.len*beat(),T.bass.gain,T.bass.wave,false);

  if(i%T.arp.every===0){
    const idx=T.arp.pat[(i/T.arp.every)%T.arp.pat.length];
    const tones=[ch[0],ch[1],ch[2],ch[0]+12];
    tone(midi(tones[idx]+12),t,beat()*.9,T.arp.gain,"triangle",true);
  }

  if(T.drums.kick.indexOf(inBar)>=0)kick(t);
  if(T.drums.snare.indexOf(inBar)>=0)snare(t);
  if(T.drums.hat.indexOf(inBar)>=0)hat(t);

  if(inBar%2===0){
    const row=T.mel[bar%T.mel.length], n=row?row[inBar/2]:null;
    if(n)tone(midi(n),t,beat()*.85,T.leadGain,T.lead,true);
  }
}
const beat=()=>60/track.bpm;
const stepDur=()=>beat()/4;
const loopLen=()=>track.bars*16;

function tick(){
  if(!playing)return;
  /* muted is the game-wide sound switch and musicOff is music only; both
     are plain globals, so they are read here rather than subscribed to. */
  if(muted||musicOff||document.hidden){ suspend(); return; }
  const a=actx; if(!a)return;
  if(a.state==="suspended")return;          // waiting on a gesture
  if(nextT<a.currentTime)nextT=a.currentTime+.06;
  while(nextT<a.currentTime+LOOKAHEAD){
    play1(step,nextT);
    nextT+=stepDur();
    step=(step+1)%loopLen();
  }
}
function suspend(){
  if(mGain)mGain.gain.cancelScheduledValues(actx.currentTime),
           mGain.gain.setTargetAtTime(0,actx.currentTime,.08);
  clearInterval(timer); timer=null; playing=false;
}
function fadeTo(v,secs){
  if(!mGain)return;
  const t=actx.currentTime;
  mGain.gain.cancelScheduledValues(t);
  mGain.gain.setValueAtTime(Math.max(mGain.gain.value,.0001),t);
  mGain.gain.linearRampToValueAtTime(v,t+secs);
}

function musicStart(){
  if(muted||musicOff)return;
  if(!build())return;
  const a=actx;
  if(a.state==="suspended")a.resume().catch(()=>{});
  if(playing)return;
  playing=true; step=0; nextT=a.currentTime+.08;
  fadeTo(VOL,1.2);
  clearInterval(timer); timer=setInterval(tick,TICK); tick();
}
function musicStop(){ suspend(); }

/* Crossfade rather than cut: the two themes share a key, so a half-second
   dip between them reads as the game changing gear. */
let swapping=null;
function musicMode(m){
  if(!TRACKS[m]||m===mode)return;
  mode=m;
  if(!playing){track=TRACKS[m];return;}
  fadeTo(0,.4); clearTimeout(swapping);
  swapping=setTimeout(()=>{
    track=TRACKS[mode]; step=0; nextT=actx.currentTime+.06; fadeTo(VOL,.7);
  },430);
}

/* The challenge flag is `.mg` on #editor — the same class the CSS reads,
   and the reason nothing else in the game has to know music exists.
   (mgState is a top-level let, so it never lands on window.) */
function watch(){
  const ed=document.getElementById("editor"); if(!ed)return;
  const sync=()=>musicMode(ed.classList.contains("mg")?"focus":"world");
  new MutationObserver(sync).observe(ed,{attributes:true,attributeFilter:["class"]});
  sync();
}

/* Autoplay policy: the context stays suspended until a real gesture, so
   arm on the first one and let Play be the usual trigger. */
function arm(){
  const go=()=>{ musicStart(); };
  document.addEventListener("pointerdown",go,{once:true});
  document.addEventListener("keydown",go,{once:true});
  const p=document.getElementById("playBtn");
  if(p)p.addEventListener("click",go);
}
document.addEventListener("visibilitychange",()=>{
  if(document.hidden)suspend();
  else if(!muted&&!musicOff&&window.__musicArmed)musicStart();
});

if(document.readyState==="loading")
  document.addEventListener("DOMContentLoaded",()=>{watch();arm();});
else {watch();arm();}
document.addEventListener("pointerdown",()=>{window.__musicArmed=1;},{once:true});

window.musicStart=musicStart; window.musicStop=musicStop; window.musicMode=musicMode;
/* Rendering the loop offline is the only way to check what it actually
   sounds like without a speaker: it catches the two faults note data can
   have that state cannot show — silence, and a mix that clips. */
function render(secs,which){
  const OC=window.OfflineAudioContext||window.webkitOfflineAudioContext;
  if(!OC)return Promise.resolve(null);
  const keep={A,bus,mGain,echo,noise,track,step};
  const oc=new OC(1,Math.ceil(44100*secs),44100);
  bus=mGain=echo=noise=null;
  build(oc); mGain.gain.value=VOL;
  track=TRACKS[which]||TRACKS.world;
  let t=0,i=0;
  while(t<secs){ play1(i%loopLen(),t); t+=stepDur(); i++; }
  return oc.startRendering().then(buf=>{
    const d=buf.getChannelData(0);
    let peak=0,sum=0;
    for(let k=0;k<d.length;k++){const v=Math.abs(d[k]);if(v>peak)peak=v;sum+=d[k]*d[k];}
    A=keep.A;bus=keep.bus;mGain=keep.mGain;echo=keep.echo;noise=keep.noise;
    track=keep.track;step=keep.step;
    return {peak:+peak.toFixed(4),rms:+Math.sqrt(sum/d.length).toFixed(4),notes:i};
  });
}

window.CC_MUSIC={
  render,
  state:()=>({playing,mode,step,scheduled,
              ctx:actx?actx.state:null,
              gain:mGain?+mGain.gain.value.toFixed(3):null,
              timer:!!timer}),
  tracks:TRACKS
};
})();
