"use strict";
/* =====================================================================
   CodeCraft — music
   ---------------------------------------------------------------------
   Two looping themes, generated by the same Web Audio graph the blips in
   fx.js already use. There is no audio file in this repo and this does not
   add one: a recorded loop is 1-3MB per track, needs a licence you have to
   be able to show a store reviewer, and has to be cached for offline. The
   whole of both themes below is a few hundred bytes of note data.

   It also buys something a recording cannot: the music follows the game.
   Entering a challenge crossfades to a tighter, faster theme in the
   relative minor, and leaving crossfades back.

   Three rules it has to keep:
     1. Never start without a gesture. Browsers suspend AudioContext until
        the user acts, and a game that fights that policy is a game that
        sometimes has no sound at all.
     2. Never drown the blips. sfx() peaks at .08 per note; music sits
        under that and everything routes through one master gain.
     3. Never run when nobody is listening. Hidden tab, muted, or music
        switched off — the scheduler stops, it does not just go quiet.
   ===================================================================== */
(function(){
if(window.__music)return; window.__music=1;

/* ---------------- the two themes ----------------
   MIDI numbers. 60 is middle C. Chords are [root, third, fifth] and the
   arp walks them; `mel` is [step, note, beats] on a 16th-note grid where a
   bar is 16 steps.

   World is C major and Focus is A minor — relative keys, the same seven
   notes, so a crossfade between them never lands on a wrong note. */
const TRACKS={
  world:{
    bpm:82, bars:8, hat:false,
    /* I - V - vi - IV, two bars each. The friendliest progression there
       is, and the reason the world theme can loop for an hour. */
    prog:[{r:48,c:[48,52,55]},{r:43,c:[43,47,50]},
          {r:45,c:[45,48,52]},{r:41,c:[41,45,48]}],
    barsPerChord:2,
    arpEvery:2,                 // eighth notes
    arpSteps:[0,1,2,3,2,1,0,1],
    bassSteps:[0,8], bassLen:2.2,
    mel:[[0,64,1.5],[8,67,1.5],
         [32,74,1],[38,71,.75],[44,67,1.5],
         [64,72,1.5],[72,69,2],
         [96,69,1],[102,72,1],[108,74,2]]
  },
  focus:{
    bpm:104, bars:4, hat:true,
    /* i - VI - III - VII, one bar each: the same four chords as the world
       theme read from its relative minor, moving twice as fast. */
    prog:[{r:45,c:[45,48,52]},{r:41,c:[41,45,48]},
          {r:48,c:[48,52,55]},{r:43,c:[43,47,50]}],
    barsPerChord:1,
    arpEvery:1,                 // sixteenths — this is the "get on with it"
    arpSteps:[0,1,2,1,2,3,2,1,0,1,2,1,2,3,2,1],
    bassSteps:[0,2,4,6,8,10,12,14], bassLen:.42,
    mel:[[0,69,.75],[6,72,.75],[32,67,.75],[38,72,1.5]]
  }
};

const VOL=0.46;               // master ceiling; sfx peaks at .08 per blip
const LOOKAHEAD=0.30;           // seconds of notes scheduled in advance
const TICK=110;                 // ms between scheduler wake-ups

const midi=n=>440*Math.pow(2,(n-69)/12);

let A=null;                     // the context every node below is built on
let bus=null,mGain=null,echo=null,noise=null;
let timer=null,playing=false,mode="world",track=TRACKS.world;
let step=0,nextT=0,scheduled=0;

/* fx.js owns `actx` and creates it lazily on the first blip. Share it, so
   the game only ever has one AudioContext — Safari caps them and a second
   one is how you get silence on iOS. */
function audio(){
  try{
    if(!actx)actx=new (window.AudioContext||window.webkitAudioContext)();
    A=actx; return actx;
  }catch(_){return null;}
}

function build(a0){
  const a=a0||audio(); if(!a)return false;
  if(!a0&&bus)return true;
  A=a;
  mGain=a.createGain(); mGain.gain.value=0; mGain.connect(a.destination);
  const lp=a.createBiquadFilter();
  lp.type="lowpass"; lp.frequency.value=2600; lp.Q.value=.6;
  lp.connect(mGain);
  bus=a.createGain(); bus.gain.value=1; bus.connect(lp);
  /* One short delay, fed only by the arp. It is the difference between
     "four oscillators" and "a room". */
  const d=a.createDelay(1), fb=a.createGain();
  d.delayTime.value=.3; fb.gain.value=.26;
  d.connect(fb); fb.connect(d); d.connect(bus);
  echo=a.createGain(); echo.gain.value=.5; echo.connect(d);
  // one second of white noise, reused for every hat
  noise=a.createBuffer(1,a.sampleRate,a.sampleRate);
  const ch=noise.getChannelData(0);
  for(let i=0;i<ch.length;i++)ch[i]=Math.random()*2-1;
  return true;
}

function tone(f,t,dur,gain,type,send){
  const a=A;
  const o=a.createOscillator(),g=a.createGain();
  o.type=type; o.frequency.setValueAtTime(f,t);
  g.gain.setValueAtTime(.0001,t);
  g.gain.linearRampToValueAtTime(gain,t+.014);
  g.gain.exponentialRampToValueAtTime(Math.max(gain*.3,.0002),t+dur*.6);
  g.gain.exponentialRampToValueAtTime(.0001,t+dur);
  o.connect(g); g.connect(bus); if(send)g.connect(echo);
  o.start(t); o.stop(t+dur+.06);
  scheduled++;
}
function hat(t){
  const a=A;
  const s=a.createBufferSource(); s.buffer=noise;
  const hp=a.createBiquadFilter(); hp.type="highpass"; hp.frequency.value=7000;
  const g=a.createGain();
  g.gain.setValueAtTime(.028,t);
  g.gain.exponentialRampToValueAtTime(.0001,t+.045);
  s.connect(hp); hp.connect(g); g.connect(bus);
  s.start(t); s.stop(t+.06);
}

/* One 16th note of the loop. Everything is derived from `step`, so the
   loop has no state to drift out of sync. */
function play1(i,t){
  const T=track, bar=Math.floor(i/16), inBar=i%16;
  const ch=T.prog[Math.floor(bar/T.barsPerChord)%T.prog.length];

  if(T.bassSteps.indexOf(inBar)>=0)
    tone(midi(ch.r-12),t,T.bassLen*beat(),.12,"sine",false);

  if(i%T.arpEvery===0){
    const idx=T.arpSteps[(i/T.arpEvery)%T.arpSteps.length];
    const tones=[ch.c[0],ch.c[1],ch.c[2],ch.c[0]+12];
    tone(midi(tones[idx]+12),t,beat()*.9,.045,"triangle",true);
  }
  if(T.hat&&inBar%4===2)hat(t);

  for(const m of T.mel)
    if(m[0]===i)tone(midi(m[1]),t,m[2]*beat(),.075,"triangle",true);
}
const beat=()=>60/track.bpm;
const stepDur=()=>beat()/4;
const loopLen=()=>track.bars*16;

function tick(){
  if(!playing)return;
  /* muted is the game-wide sound switch and musicOff is music only; both
     are plain globals, so they are read here rather than subscribed to. */
  if(muted||musicOff||document.hidden){ suspend(); return; }
  const a=actx; if(!a)return;
  if(a.state==="suspended")return;          // waiting on a gesture
  if(nextT<a.currentTime)nextT=a.currentTime+.06;
  while(nextT<a.currentTime+LOOKAHEAD){
    play1(step,nextT);
    nextT+=stepDur();
    step=(step+1)%loopLen();
  }
}
function suspend(){
  if(mGain)mGain.gain.cancelScheduledValues(actx.currentTime),
           mGain.gain.setTargetAtTime(0,actx.currentTime,.08);
  clearInterval(timer); timer=null; playing=false;
}
function fadeTo(v,secs){
  if(!mGain)return;
  const t=actx.currentTime;
  mGain.gain.cancelScheduledValues(t);
  mGain.gain.setValueAtTime(Math.max(mGain.gain.value,.0001),t);
  mGain.gain.linearRampToValueAtTime(v,t+secs);
}

function musicStart(){
  if(muted||musicOff)return;
  if(!build())return;
  const a=actx;
  if(a.state==="suspended")a.resume().catch(()=>{});
  if(playing)return;
  playing=true; step=0; nextT=a.currentTime+.08;
  fadeTo(VOL,1.2);
  clearInterval(timer); timer=setInterval(tick,TICK); tick();
}
function musicStop(){ suspend(); }

/* Crossfade rather than cut: the two themes share a key, so a half-second
   dip between them reads as the game changing gear. */
let swapping=null;
function musicMode(m){
  if(!TRACKS[m]||m===mode)return;
  mode=m;
  if(!playing){track=TRACKS[m];return;}
  fadeTo(0,.4); clearTimeout(swapping);
  swapping=setTimeout(()=>{
    track=TRACKS[mode]; step=0; nextT=actx.currentTime+.06; fadeTo(VOL,.7);
  },430);
}

/* The challenge flag is `.mg` on #editor — the same class the CSS reads,
   and the reason nothing else in the game has to know music exists.
   (mgState is a top-level let, so it never lands on window.) */
function watch(){
  const ed=document.getElementById("editor"); if(!ed)return;
  const sync=()=>musicMode(ed.classList.contains("mg")?"focus":"world");
  new MutationObserver(sync).observe(ed,{attributes:true,attributeFilter:["class"]});
  sync();
}

/* Autoplay policy: the context stays suspended until a real gesture, so
   arm on the first one and let Play be the usual trigger. */
function arm(){
  const go=()=>{ musicStart(); };
  document.addEventListener("pointerdown",go,{once:true});
  document.addEventListener("keydown",go,{once:true});
  const p=document.getElementById("playBtn");
  if(p)p.addEventListener("click",go);
}
document.addEventListener("visibilitychange",()=>{
  if(document.hidden)suspend();
  else if(!muted&&!musicOff&&window.__musicArmed)musicStart();
});

if(document.readyState==="loading")
  document.addEventListener("DOMContentLoaded",()=>{watch();arm();});
else {watch();arm();}
document.addEventListener("pointerdown",()=>{window.__musicArmed=1;},{once:true});

window.musicStart=musicStart; window.musicStop=musicStop; window.musicMode=musicMode;
/* Rendering the loop offline is the only way to check what it actually
   sounds like without a speaker: it catches the two faults note data can
   have that state cannot show — silence, and a mix that clips. */
function render(secs,which){
  const OC=window.OfflineAudioContext||window.webkitOfflineAudioContext;
  if(!OC)return Promise.resolve(null);
  const keep={A,bus,mGain,echo,noise,track,step};
  const oc=new OC(1,Math.ceil(44100*secs),44100);
  bus=mGain=echo=noise=null;
  build(oc); mGain.gain.value=VOL;
  track=TRACKS[which]||TRACKS.world;
  let t=0,i=0;
  while(t<secs){ play1(i%loopLen(),t); t+=stepDur(); i++; }
  return oc.startRendering().then(buf=>{
    const d=buf.getChannelData(0);
    let peak=0,sum=0;
    for(let k=0;k<d.length;k++){const v=Math.abs(d[k]);if(v>peak)peak=v;sum+=d[k]*d[k];}
    A=keep.A;bus=keep.bus;mGain=keep.mGain;echo=keep.echo;noise=keep.noise;
    track=keep.track;step=keep.step;
    return {peak:+peak.toFixed(4),rms:+Math.sqrt(sum/d.length).toFixed(4),notes:i};
  });
}

window.CC_MUSIC={
  render,
  state:()=>({playing,mode,step,scheduled,
              ctx:actx?actx.state:null,
              gain:mGain?+mGain.gain.value.toFixed(3):null,
              timer:!!timer}),
  tracks:TRACKS
};
})();
